# Generated by Django 3.2.12 on 2022-04-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecters',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
