# Generated by Django 3.2.12 on 2022-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_auto_20220405_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecters',
            name='enrollment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prospecters',
            name='payment_period',
            field=models.CharField(choices=[('SEMANAL', 'SEMANAL'), ('MENSUAL', 'MENSUAL')], default='SEMANAL', max_length=8),
        ),
    ]
