# Generated by Django 3.2.12 on 2022-04-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_auto_20220405_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecters',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
