# Generated by Django 3.2.12 on 2022-04-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0007_alter_prospecters_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecters',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
